/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Drone3d(props) {
  const group = useRef()
  // Commenting out the GLTF loading line
  // const { nodes, materials, animations } = useGLTF('/static/drone.glb')
  const { actions } = useAnimations([], group) // Updated to avoid errors
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="RootNode0" scale={0.15}>
          {/* Add any necessary geometry or meshes here */}
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/static/drone.glb') // Comment this line as well
